### ISSUE TITLE
How TO

### ISSUE THREAD

**Issue by PsychoE** [Warsaalk/trashsim-public#1]
any chance to add How TO instruction for setup?

**Comment by stevecohenfr** [comment]
I spent a lot of time trying to make it works on my own server. After installing everything, debugging, i have a blank page with "hello world". Nothing more. The routing system is not working but i don't know why

**Comment by klaasvp** [comment]
The attached readme file should be enough for people with some PHP knowledge, provided some look-up work, to get the project online.

The purpose of this repository was to make code public not so anyone could just run it on any computer and server.

I recommend that developers only use the code as the basis for something they reboot themselves. The front-end code is very outdated and should really be rewritten.

**Comment by stevecohenfr** [comment]
Thanks, i finally made it works yesterday 😊
