### ISSUE TITLE
env.ini

### ISSUE THREAD

**Issue by KreK93** [Warsaalk/trashsim-public#3]
Hello, thank you for sharing your amazing work!

I've an issue, I'm unable to load the page, it automatically redirect to *.*/public/{local}/**notsupported** page.

I addressed the issue to env.ini file location, probably. As you can see it's unable to "convert" $ENV into "assets/" position.

I tried to place env.ini everywhere without success.
Any hint ?

Thanks

<img width="1915" alt="error_trashsim" src="https://github.com/Warsaalk/trashsim-public/assets/24281678/76f75acd-b4c1-439e-9a3d-26c07db13172">

**Comment by klaasvp** [comment]
The value of the path setting should be:
![image](https://github.com/Warsaalk/trashsim-public/assets/2462755/3189bea9-bcce-4081-ad46-d834f91a2475)

The env.ini file should be in the root directory where the composer.json file is located.

**Comment by KreK93** [comment]
> The value of the path setting should be: ![image](https://private-user-images.githubusercontent.com/2462755/293012360-3189bea9-bcce-4081-ad46-d834f91a2475.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM2NzQ3NTUsIm5iZiI6MTcwMzY3NDQ1NSwicGF0aCI6Ii8yNDYyNzU1LzI5MzAxMjM2MC0zMTg5YmVhOS1iY2NlLTQwODEtYWQ0Ni1kODM0ZjkxYTI0NzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjdUMTA1NDE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWQ3OGMzYzU5ODI1M2JmMTM1ZTQyNjhiNTg2YTVkMDYwMjg3Zjk0OWMwMDdlODM0NjhkYmJmNmFlZjhjOTlhYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NKrQPxDBMZKtofspAbElI3vy-taek7DPHCkLELkSABc)
> 
> The env.ini file should be in the root directory where the composer.json file is located.

I've done that, but nothing changed.
I tried to restart the server, re-compile it, but nothing.

**Comment by KreK93** [comment]
I modified the file config.ini located in app/config
<img width="173" alt="error_trashsim" src="https://github.com/Warsaalk/trashsim-public/assets/24281678/66bd673c-1b28-45b6-8e47-0f9ad6fb33c0">

deleted the browser cache, and now it works :D

Thank you again for your work!
